/* Optional development-only smoke tests: NODE_PATH must include Playwright. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:process.env.SKYPLANE_BROWSER||'msedge',args:['--disable-gpu']});
  const page=await browser.newPage({viewport:{width:1440,height:1080},deviceScaleFactor:1});
  const errors=[],requests=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
  await page.goto(process.env.SKYPLANE_URL||'http://127.0.0.1:4173');
  await page.click('[data-action="new-world"]');await page.fill('#new-world-name','Seabreeze Island');await page.click('#create-world-form button[type="submit"]');await page.click('[data-page="overview"].nav-item');
  await page.waitForSelector('#airport-canvas');
  await page.waitForTimeout(400);
    await page.screenshot({path:path.join(__dirname,'screenshot-overview-desktop.png'),fullPage:true});
  assert.equal(await page.locator('h1').textContent(),'A little airport. Big plans.');
  assert.equal(await page.evaluate(()=>SkyPlane.snapshot().state.settings.graphics),'low');
  await page.click('[data-page="build"].nav-item');
  await page.click('[data-action="build"][data-id="terminal"]');
  assert.equal(await page.evaluate(()=>SkyPlane.snapshot().state.buildings.terminal),1);
  await page.click('[data-page="team"].nav-item');await page.click('[data-action="hire"][data-id="cabin"]');
  assert.equal(await page.evaluate(()=>SkyPlane.snapshot().state.staff.cabin),1);
  await page.click('#switch-role');await page.click('[data-action="role"][data-id="checkin"]');
  await page.click('[data-action="answer"][data-id="0"]');
  assert.equal(await page.evaluate(()=>SkyPlane.snapshot().state.tasks),1);
  assert.ok((await page.locator('.workstation').textContent()).includes('Another little win'));
  await page.click('[data-page="budget"].nav-item');assert.ok((await page.locator('h1').textContent()).includes('green'));
  await page.click('[data-action="loan"]');await page.click('[data-action="confirm-loan"]');
  assert.equal(await page.evaluate(()=>SkyPlane.snapshot().state.debt),5000);await page.click('[data-action="repay"]');assert.equal(await page.evaluate(()=>SkyPlane.snapshot().state.debt),0);
  await page.click('[data-page="settings"].nav-item');await page.selectOption('#setting-difficulty','hard');await page.selectOption('#setting-weather','sunset');
  await page.click('[data-action="skin"][data-id="#6ca7ae"]');
  await page.reload();await page.click('[data-action="load-world"]');assert.equal(await page.evaluate(()=>SkyPlane.snapshot().state.settings.difficulty),'hard');assert.equal(await page.evaluate(()=>SkyPlane.snapshot().state.skin),'#6ca7ae');
  await page.click('[data-page="operations"].nav-item');await page.click('[data-action="course"]');await page.fill('#course-gates','10');await page.click('[data-action="save-course"]');
  assert.equal(await page.evaluate(()=>SkyPlane.snapshot().state.course.gates),10);
  await page.click('[data-page="tutorial"].nav-item');assert.equal(await page.locator('.lesson').count(),9);
  await page.screenshot({path:path.join(__dirname,'screenshot-tutorial-desktop.png'),fullPage:true});
  await page.click('[data-action="brief"][data-id="training"]');await page.click('[data-action="launch"]');
  await page.keyboard.press('f');await page.keyboard.down('Shift');await page.waitForTimeout(2000);await page.keyboard.up('Shift');
  const f=await page.evaluate(()=>SkyPlane.snapshot().flight);assert.ok(f.throttle>.35);assert.equal(f.flaps,1);
  await page.screenshot({path:path.join(__dirname,'screenshot-flight-desktop.png')});
  await page.click('#replay-button');assert.equal(await page.evaluate(()=>SkyPlane.snapshot().replay),true);
  const replayAt=await page.evaluate(()=>SkyPlane.snapshot().flight.time);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>SkyPlane.snapshot().flight.time),replayAt);
  await page.click('#replay-button');assert.equal(await page.evaluate(()=>SkyPlane.snapshot().replay),false);
  await page.keyboard.press('Escape');const t=await page.evaluate(()=>SkyPlane.snapshot().flight.time);await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>SkyPlane.snapshot().flight.time),t);
  await page.click('[data-action="resume"]');await page.click('#flight-exit');await page.click('[data-action="end-flight"]');
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(__dirname,'screenshot-overview-mobile.png'),fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.click('#mobile-menu');await page.click('[data-page="settings"].nav-item');assert.equal(await page.locator('#setting-graphics').count(),1);
  await page.screenshot({path:path.join(__dirname,'screenshot-settings-mobile.png'),fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  assert.deepEqual(errors,[]);assert.equal(requests.filter(x=>!x.startsWith('http://127.0.0.1:4173')&&!x.startsWith('data:')).length,0);
  console.log('PASS: desktop and mobile UI, construction, staff, roles, loans, settings, persistence, race editor, tutorial, flight input, pause, and no external requests.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
