const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:process.env.SKYPLANE_BROWSER||'msedge',args:['--disable-gpu']});
  const page=await browser.newPage({viewport:{width:1440,height:1120}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  const output=__dirname; // screenshots land next to the game as screenshot-*.png
  await page.goto('http://127.0.0.1:4173');await page.waitForSelector('#menu-canvas');
  assert.equal(await page.evaluate(()=>SkyPlane.snapshot().inMenu),true);assert.equal(await page.locator('.world-card').count(),0);
  await page.waitForTimeout(200);await page.screenshot({path:path.join(output,'screenshot-menu-empty.png'),fullPage:true});
  await page.click('[data-action="new-world"]');await page.fill('#new-world-name','Cloud Nine Airfield');await page.check('input[name="world-mode"][value="flight"]');await page.uncheck('#new-world-tutorial');
  await page.screenshot({path:path.join(output,'screenshot-create-world.png')});
  await page.click('#create-world-form button[type="submit"]');
  let snap=await page.evaluate(()=>SkyPlane.snapshot());const flightId=snap.activeWorldId;
  assert.equal(snap.state.world.business,false);assert.equal(snap.state.world.tutorial,false);assert.equal(snap.page,'overview');assert.equal(snap.state.cash,0);assert.equal(snap.state.world.mode,'flight');assert.ok(await page.locator('#airport-canvas').isVisible());
  assert.equal(await page.locator('[data-page="build"].nav-item').isVisible(),false);assert.equal(await page.locator('[data-page="tutorial"].nav-item').isVisible(),false);assert.equal(await page.locator('[data-action="brief"][data-id="training"]').count(),0);
  await page.waitForTimeout(350);snap=await page.evaluate(()=>SkyPlane.snapshot());assert.equal(snap.state.expenses,0);assert.equal(snap.state.completed,0);
  await page.click('[data-page="settings"].nav-item');await page.fill('#world-name','Cloud Nine International');await page.click('#world-rename-form button[type="submit"]');await page.selectOption('#setting-weather','sunset');
  assert.equal(await page.locator('.world-config .locked-label').count(),3);assert.equal(await page.locator('.world-config input[type="checkbox"]').count(),0);
  await page.click('[data-page="operations"].nav-item');await page.click('[data-action="brief"][data-id="passenger"]');assert.ok(!(await page.locator('.modal').textContent()).includes('airport budget'));
  await page.click('[data-action="launch"]');await page.waitForTimeout(100);assert.equal(await page.locator('#flight-hint').isVisible(),false);await page.click('#flight-exit');await page.click('[data-action="end-flight"]');
  await page.click('.sidebar [data-action="main-menu"].nav-item');
  const time=await page.evaluate(()=>SkyPlane.snapshot().state.seconds);await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>SkyPlane.snapshot().state.seconds),time);
  await page.click('[data-action="new-world"]');await page.fill('#new-world-name','Seabreeze Island');await page.click('#create-world-form button[type="submit"]');
  snap=await page.evaluate(()=>SkyPlane.snapshot());const businessId=snap.activeWorldId;assert.equal(snap.state.world.business,true);assert.equal(snap.state.world.tutorial,true);assert.equal(snap.page,'tutorial');
  await page.click('[data-page="build"].nav-item');await page.click('[data-action="build"][data-id="terminal"]');await page.click('.sidebar [data-action="main-menu"].nav-item');
  await page.waitForTimeout(200);await page.screenshot({path:path.join(output,'screenshot-main-menu-desktop.png'),fullPage:true});
  assert.equal(await page.locator('.world-card').count(),2);
  await page.fill('#world-search','cloud');assert.equal(await page.locator('.world-card').count(),1);await page.fill('#world-search','missing');assert.equal(await page.locator('.world-card').count(),0);await page.fill('#world-search','');
  await page.click(`.world-card [data-action="load-world"][data-id="${flightId}"]`);snap=await page.evaluate(()=>SkyPlane.snapshot());assert.equal(snap.state.world.name,'Cloud Nine International');assert.equal(snap.state.world.business,false);assert.equal(snap.state.settings.weather,'sunset');assert.equal(snap.state.cash,0);
  await page.click('.sidebar [data-action="main-menu"].nav-item');await page.reload();assert.equal(await page.locator('.world-card').count(),2);
  await page.click(`.world-card [data-action="world-settings"][data-id="${businessId}"]`);assert.equal(await page.locator('.modal .locked-label').count(),3);await page.fill('#edit-world-name','Seabreeze International');await page.click('#menu-world-rename button[type="submit"]');
  await page.click(`.world-card [data-action="load-world"][data-id="${businessId}"]`);snap=await page.evaluate(()=>SkyPlane.snapshot());assert.equal(snap.state.buildings.terminal,1);assert.equal(snap.state.settings.weather,'clear');assert.equal(snap.state.world.name,'Seabreeze International');assert.equal(snap.state.world.tutorial,true);
  await page.click('.sidebar [data-action="main-menu"].nav-item');await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);await page.screenshot({path:path.join(output,'screenshot-main-menu-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.click('[data-action="new-world"]');await page.screenshot({path:path.join(output,'screenshot-create-world-mobile.png')});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.click('[data-action="close-modal"]');
  await page.click(`.world-card [data-action="world-settings"][data-id="${flightId}"]`);await page.click('[data-action="delete-world"]');await page.click('[data-action="close-modal"]');assert.equal(await page.locator('.world-card').count(),2);
  await page.click(`.world-card [data-action="world-settings"][data-id="${flightId}"]`);await page.click('[data-action="delete-world"]');await page.click('[data-action="confirm-delete-world"]');assert.equal(await page.locator('.world-card').count(),1);assert.equal(await page.evaluate(()=>SkyPlane.snapshot().library.worlds[0].id),businessId);
  const migrated=await browser.newPage();migrated.on('pageerror',e=>errors.push(e.message));await migrated.addInitScript(()=>{if(!localStorage.getItem('skyplane-worlds-v2'))localStorage.setItem('skyplane-save-v1',JSON.stringify({version:1,cash:12345,missions:7,buildings:{terminal:2}}));});await migrated.goto('http://127.0.0.1:4173');assert.equal(await migrated.locator('.world-card').count(),1);await migrated.click('[data-action="load-world"]');assert.equal(await migrated.evaluate(()=>SkyPlane.snapshot().state.missions),7);assert.equal(await migrated.evaluate(()=>SkyPlane.snapshot().state.buildings.terminal),2);
  assert.deepEqual(errors,[]);console.log('PASS: menu, world creation choices, flight-only mode, tutorial on/off, locked settings, rename, isolated progression, search, reload, migration, mobile layout, and delete confirmation.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
